name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 자정에 실행
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        repository: 'packetinside/C2-Tracker'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git
      run: |
        git config --global user.name 'packetinside'
        git config --global user.email 'packetinside@gmail.com'

    - name: Add upstream repository
      run: |
        git remote add upstream https://github.com/montysecurity/C2-Tracker.git
        git fetch upstream
        git checkout main
        git merge upstream/main
        git push origin main
